Lang: "zh_CN"
Type:
  Vault:
    name: "货币"
  "世界币":
    name: "&e世界币"
    take:
      - "abo editmo 世界币 <value> - <player>"
    add:
      - "abo editmo 世界币 <value> + <player>"
    get: "%aboe_世界币_0_me_0%"