#不要让商店以 default 为名称
#这是所有商店的默认配置
#如果要修改某个商店的配置请复制本文将然后修改 Shop: ""
Shop: "default"
Layout:
  - "####A####"
  - "#@@@@@@@#"
  - "#@@@@@@@#"
  - "#@@@@@@@#"
  - "#@@@@@@@#"
  - "##B#E#C##"
#商品
Commodity: "@"
#创建按钮
CreateItem: "A"
#修改展示名按钮
ReName: "E"
#翻页按钮
NextItem:
  slot: "B"
  #有下一页展示的物品
  #物品的详细写法可以参考 https://github.com/CryptoMorin/XSeries/wiki/XItemStack
  has:
    material: "SPECTRAL_ARROW"
    name: "§f下一页"
  normal:
    material: "ARROW"
    name: "§7下一页"
PreviousItem:
  slot: "C"
  has:
    material: "SPECTRAL_ARROW"
    name: "§f上一页"
  normal:
    material: "ARROW"
    name: "§7上一页"

OtherItem:
  #这是其他物品按钮
  #action里的是kether脚本
  #https://kether.tabooproject.org/
  "D":
    item:
      material: "SPECTRAL_ARROW"
      name: "§额外的按钮"
    action:
      left:
        - command "say hi" as op
      left_shift:
        - command "say hi" as op
      right:
        - command "say hi" as op
      right_shift:
        - command "say hi" as op